------------------------------------------------------
-- AUTOR       : NTT DATA CENTERS - SEVILLA
-- DESCRIPCIÓN : JAVA - JDBC - ORACLE - EJEMPLO
-- RESPONSABLE : JUAN ALEJANDRO TÉLLEZ RUBIO
------------------------------------------------------

-- BORRADO PREVIO.
DROP TABLE NTTDATA_ORACLE_SOCCER_TEAM;
DROP SEQUENCE NTTDATA_ORACLE_SOCCER_TEAM_SEQ;
DROP TABLE NTTDATA_ORACLE_SOCCER_PLAYER;
DROP SEQUENCE NTTDATA_ORACLE_SOCCER_PLAYER_SEQ;

-- CREACIÓN DE TABLA PARA PERSONAS.
CREATE TABLE NTTDATA_ORACLE_SOCCER_TEAM (
	
	ID_SOCCER_TEAM INT NOT NULL,
	NAME VARCHAR(35),
	STADIUM VARCHAR(40),
	STADIUM_CAPACITY INT,
	FIRST_COLOR VARCHAR(10),
	SECOND_COLOR VARCHAR(10),
	THIRD_COLOR VARCHAR(10),
	CITY VARCHAR(15),
	DIVISION INT,
	NUM_NATIONAL_TROPHIES INT,
	NUM_INTERNATIONAL_TROPHIES INT,
	
	CONSTRAINT PK_SOCCER_TEAMS PRIMARY KEY (ID_SOCCER_TEAM)
);

-- DESCRIPCIÓN DE LAS COLUMNAS.
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_TEAM"."ID_SOCCER_TEAM" IS 'ID DEL EQUIPO';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_TEAM"."NAME" IS 'NOMBRE DEL EQUIPO';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_TEAM"."STADIUM" IS 'NOMBRE DEL ESTADIO';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_TEAM"."STADIUM_CAPACITY" IS 'CAPACIDAD DEL ESTADIO';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_TEAM"."FIRST_COLOR" IS 'PRIMER COLOR';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_TEAM"."SECOND_COLOR" IS 'SEGUNDO COLOR';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_TEAM"."THIRD_COLOR" IS 'TERCER COLOR';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_TEAM"."CITY" IS 'CIUDAD DEL CLUB';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_TEAM"."DIVISION" IS 'DIVISIÓN O CATEGORÍA EN QUE PARTICIPA';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_TEAM"."NUM_NATIONAL_TROPHIES" IS 'NÚMERO DE TROFEOS NACIONALES';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_TEAM"."NUM_INTERNATIONAL_TROPHIES" IS 'NÚMERO DE TROFEOS INTERNACIONALES';

-- SECUENCIA QUE IRÁ ASOCIADA A LA TABLA.
CREATE SEQUENCE  "NTTDATA_ORACLE_SOCCER_TEAM_SEQ" MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;

-- AÑADIDO DE EQUIPOS.
INSERT INTO NTTDATA_ORACLE_SOCCER_TEAM (ID_SOCCER_TEAM, NAME, STADIUM, STADIUM_CAPACITY, FIRST_COLOR, SECOND_COLOR, THIRD_COLOR, CITY, DIVISION, NUM_NATIONAL_TROPHIES, NUM_INTERNATIONAL_TROPHIES)
VALUES (NTTDATA_ORACLE_SOCCER_TEAM_SEQ.NEXTVAL, 'SEVILLA FÚTBOL CLUB', 'RAMÓN SÁNCHEZ-PIZJUÁN', 47074, 'BLANCO', 'ROJO', 'NEGRO', 'SEVILLA', 1, 7, 6);
INSERT INTO NTTDATA_ORACLE_SOCCER_TEAM (ID_SOCCER_TEAM, NAME, STADIUM, STADIUM_CAPACITY, FIRST_COLOR, SECOND_COLOR, THIRD_COLOR, CITY, DIVISION, NUM_NATIONAL_TROPHIES, NUM_INTERNATIONAL_TROPHIES)
VALUES (NTTDATA_ORACLE_SOCCER_TEAM_SEQ.NEXTVAL, 'REAL BETIS BALOMPIÉ', 'BENITO VILLAMARÍN', 67584, 'BLANCO', 'VERDE', 'GRIS', 'SEVILLA', 1, 3, 0);
INSERT INTO NTTDATA_ORACLE_SOCCER_TEAM (ID_SOCCER_TEAM, NAME, STADIUM, STADIUM_CAPACITY, FIRST_COLOR, SECOND_COLOR, THIRD_COLOR, CITY, DIVISION, NUM_NATIONAL_TROPHIES, NUM_INTERNATIONAL_TROPHIES)
VALUES (NTTDATA_ORACLE_SOCCER_TEAM_SEQ.NEXTVAL, 'GRANADA CLUB DE FÚTBOL', 'NUEVO LOS CÁRMENES', 19336, 'ROJO', 'AZUL', 'BLANCO', 'GRANADA', 1, 0, 0);
INSERT INTO NTTDATA_ORACLE_SOCCER_TEAM (ID_SOCCER_TEAM, NAME, STADIUM, STADIUM_CAPACITY, FIRST_COLOR, SECOND_COLOR, THIRD_COLOR, CITY, DIVISION, NUM_NATIONAL_TROPHIES, NUM_INTERNATIONAL_TROPHIES)
VALUES (NTTDATA_ORACLE_SOCCER_TEAM_SEQ.NEXTVAL, 'CÁDIZ CLUB DE FÚTBOL', 'RAMÓN DE CARRANZA', 20724, 'AMARILLO', 'AZUL', 'NEGRO', 'CÁDIZ', 1, 0, 0);
INSERT INTO NTTDATA_ORACLE_SOCCER_TEAM (ID_SOCCER_TEAM, NAME, STADIUM, STADIUM_CAPACITY, FIRST_COLOR, SECOND_COLOR, THIRD_COLOR, CITY, DIVISION, NUM_NATIONAL_TROPHIES, NUM_INTERNATIONAL_TROPHIES)
VALUES (NTTDATA_ORACLE_SOCCER_TEAM_SEQ.NEXTVAL, 'MÁLAGA CLUB DE FÚTBOL', 'LA ROSALEDA', 30044, 'BLANCO', 'AZUL', 'MORADO', 'MÁLAGA', 2, 0, 1);
INSERT INTO NTTDATA_ORACLE_SOCCER_TEAM (ID_SOCCER_TEAM, NAME, STADIUM, STADIUM_CAPACITY, FIRST_COLOR, SECOND_COLOR, THIRD_COLOR, CITY, DIVISION, NUM_NATIONAL_TROPHIES, NUM_INTERNATIONAL_TROPHIES) 
VALUES (NTTDATA_ORACLE_SOCCER_TEAM_SEQ.NEXTVAL, 'REAL CLUB RECREATIVO DE HUELVA', 'NUEVO COLOMBINO', 21670, 'BLANCO', 'AZUL', 'NARANJA', 'HUELVA', 4, 0, 0);
INSERT INTO NTTDATA_ORACLE_SOCCER_TEAM (ID_SOCCER_TEAM, NAME, STADIUM, STADIUM_CAPACITY, FIRST_COLOR, SECOND_COLOR, THIRD_COLOR, CITY, DIVISION, NUM_NATIONAL_TROPHIES, NUM_INTERNATIONAL_TROPHIES)
VALUES (NTTDATA_ORACLE_SOCCER_TEAM_SEQ.NEXTVAL, 'UNIÓN DEPORTIVA ALMERÍA', 'ESTADIO DE LOS JUEGOS MEDITERRÁNEOS', 15274, 'ROJO', 'BLANCO', 'NEGRO', 'ALMERÍA', 2, 0, 0);
INSERT INTO NTTDATA_ORACLE_SOCCER_TEAM (ID_SOCCER_TEAM, NAME, STADIUM, STADIUM_CAPACITY, FIRST_COLOR, SECOND_COLOR, THIRD_COLOR, CITY, DIVISION, NUM_NATIONAL_TROPHIES, NUM_INTERNATIONAL_TROPHIES) 
VALUES (NTTDATA_ORACLE_SOCCER_TEAM_SEQ.NEXTVAL, 'REAL JAÉN CLUB DE FÚTBOL', 'LA VICTORIA', 15569, 'BLANCO', 'MORADO', 'VERDE', 'JAÉN', 4, 0, 0);
INSERT INTO NTTDATA_ORACLE_SOCCER_TEAM (ID_SOCCER_TEAM, NAME, STADIUM, STADIUM_CAPACITY, FIRST_COLOR, SECOND_COLOR, THIRD_COLOR, CITY, DIVISION, NUM_NATIONAL_TROPHIES, NUM_INTERNATIONAL_TROPHIES)
VALUES (NTTDATA_ORACLE_SOCCER_TEAM_SEQ.NEXTVAL, 'XEREZ CLUB DEPORTIVO', 'ESTADIO DE LA JUVENTUD', 2000, 'AZUL', 'BLANCO', 'ROJO', 'CÁDIZ', 5, 0, 0);
INSERT INTO NTTDATA_ORACLE_SOCCER_TEAM (ID_SOCCER_TEAM, NAME, STADIUM, STADIUM_CAPACITY, FIRST_COLOR, SECOND_COLOR, THIRD_COLOR, CITY, DIVISION, NUM_NATIONAL_TROPHIES, NUM_INTERNATIONAL_TROPHIES) 
VALUES (NTTDATA_ORACLE_SOCCER_TEAM_SEQ.NEXTVAL,'CÓRDOBA CLUB DE FÚTBOL', 'EL ARCÁNGEL', 21822, 'BLANCO', 'VERDE', 'ROJO', 'CÓRDOBA', 4, 0, 0);

-- CREACIÓN DE TABLA PARA PERSONAS.
CREATE TABLE NTTDATA_ORACLE_SOCCER_PLAYER (
	
	ID_SOCCER_PLAYER INT NOT NULL,
	NAME VARCHAR(35),
	BIRTH_DATE DATE,
	FIRST_ROL VARCHAR(20),
	SECOND_ROL VARCHAR(20),
	ID_SOCCER_TEAM INT,
	
	CONSTRAINT PK_SOCCER_PLAYERS PRIMARY KEY(ID_SOCCER_PLAYER),
	CONSTRAINT FK_SOCCER_TEAMS FOREIGN KEY(ID_SOCCER_TEAM) REFERENCES NTTDATA_ORACLE_SOCCER_TEAM(ID_SOCCER_TEAM)
);

-- DESCRIPCIÓN DE LAS COLUMNAS.
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_PLAYER"."ID_SOCCER_PLAYER" IS 'ID DEL FUTBOLISTA';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_PLAYER"."NAME" IS 'NOMBRE DEL JUGADOR';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_PLAYER"."BIRTH_DATE" IS 'FECHA DE NACIMIENTO';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_PLAYER"."FIRST_ROL" IS 'PRIMERA POSICIÓN';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_PLAYER"."SECOND_ROL" IS 'SEGUNDA POSICIÓN';
COMMENT ON COLUMN "NTTDATA_ORACLE_SOCCER_PLAYER"."ID_SOCCER_TEAM" IS 'ID DEL EQUPO DE FÚTBOL';

-- SECUENCIA QUE IRÁ ASOCIADA A LA TABLA.
CREATE SEQUENCE  "NTTDATA_ORACLE_SOCCER_PLAYER_SEQ" MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;


-- AÑADIDO DE FUTBOLISTAS.
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL, ID_SOCCER_TEAM) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'JESÚS NAVAS', '21/11/1985', 'LAT-D', 'EXT-D', (SELECT ID_SOCCER_TEAM FROM NTTDATA_ORACLE_SOCCER_TEAM WHERE NAME = 'SEVILLA FÚTBOL CLUB'));
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL, ID_SOCCER_TEAM) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'JULES KOUNDÉ', '12/11/1998', 'CEN-D', 'LAT-D', (SELECT ID_SOCCER_TEAM FROM NTTDATA_ORACLE_SOCCER_TEAM WHERE NAME = 'SEVILLA FÚTBOL CLUB'));
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL, ID_SOCCER_TEAM) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'YOUSSEF EN-NESYRI', '01/06/1997', 'DEL', 'EXT-I', (SELECT ID_SOCCER_TEAM FROM NTTDATA_ORACLE_SOCCER_TEAM WHERE NAME = 'SEVILLA FÚTBOL CLUB'));
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL, ID_SOCCER_TEAM) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'JOAQUÍN SÁNCHEZ', '21/07/1981', 'EXT-D', 'DEL', (SELECT ID_SOCCER_TEAM FROM NTTDATA_ORACLE_SOCCER_TEAM WHERE NAME = 'REAL BETIS BALOMPIÉ'));
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL, ID_SOCCER_TEAM) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'SERGIO CANALES', '16/02/1991', 'MEC', 'PIV', (SELECT ID_SOCCER_TEAM FROM NTTDATA_ORACLE_SOCCER_TEAM WHERE NAME = 'REAL BETIS BALOMPIÉ'));
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL, ID_SOCCER_TEAM) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'NABIL FEKIR', '18/07/1993', 'MEP', 'EXT-D', (SELECT ID_SOCCER_TEAM FROM NTTDATA_ORACLE_SOCCER_TEAM WHERE NAME = 'REAL BETIS BALOMPIÉ'));
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL, ID_SOCCER_TEAM) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'GENARO', '23/03/1998', 'MEC', 'CEN', (SELECT ID_SOCCER_TEAM FROM NTTDATA_ORACLE_SOCCER_TEAM WHERE NAME = 'MÁLAGA CLUB DE FÚTBOL'));
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL, ID_SOCCER_TEAM) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'JAIRO SAMPERIO', '11/07/1993', 'MEP', 'EXT-D', (SELECT ID_SOCCER_TEAM FROM NTTDATA_ORACLE_SOCCER_TEAM WHERE NAME = 'MÁLAGA CLUB DE FÚTBOL'));
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL, ID_SOCCER_TEAM) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'ANTOÑIN', '16/04/2000', 'DEL', 'EXT', (SELECT ID_SOCCER_TEAM FROM NTTDATA_ORACLE_SOCCER_TEAM WHERE NAME = 'MÁLAGA CLUB DE FÚTBOL'));
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'PORTU', '21/05/1992', 'DEL', 'MEP');
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'CARLOS FDZ.', '24/05/1996', 'DEL', 'MEP');
INSERT INTO NTTDATA_ORACLE_SOCCER_PLAYER (ID_SOCCER_PLAYER, NAME, BIRTH_DATE, FIRST_ROL, SECOND_ROL) 
VALUES (NTTDATA_ORACLE_SOCCER_PLAYER_SEQ.NEXTVAL, 'ILLARRAMENDI', '31/03/1990', 'MEC', 'PIV');

COMMIT;