------------------------------------------------------
-- Autor       : NTT Data Sevilla
-- Descripción : Script 0 MySQL - Formación SQL
-- Responsable : Juan Alejandro Téllez Rubio
------------------------------------------------------

-- Eliminación de esquema.
DROP SCHEMA NTTDATA_FPDUAL_MYSQL;

-- Creación de esquema.
CREATE SCHEMA IF NOT EXISTS NTTDATA_FPDUAL_MYSQL DEFAULT CHARACTER SET UTF8MB4;

-- Uso de esquema.
USE NTTDATA_FPDUAL_MYSQL;

-- Creación de tabla para personas.
CREATE TABLE FPD_NTTDATA_PEOPLE(
	
	PERSON_ID INT NOT NULL COMMENT 'PK - ID PERSONA',
	NAME VARCHAR(40) COMMENT 'NOMBRE DE LA PERSONA',
	IS_TRAINER BOOLEAN COMMENT 'INDICADOR DE FORMADOR/A',
	MOBILE_NUMBER VARCHAR(9) COMMENT 'TELEFONO MOVIL'

);

ALTER TABLE FPD_NTTDATA_PEOPLE COMMENT = 'TABLA DE PERSONAS';

-- Creación de tabla para alumnos.
CREATE TABLE FPD_NTTDATA_STUDENT (
	
	STUDENT_ID INT NOT NULL COMMENT 'PK - ID ALUMNO/A',
	SCHOOL_ID INT NOT NULL COMMENT 'FK - ID CENTRO EDUCATIVO',
	NAME VARCHAR(40) COMMENT 'NOMBRE CENTRO EDUCATIVO'

);

-- Creación de tabla para institutos.
CREATE TABLE FPD_NTTDATA_SCHOOL (
	
	SCHOOL_ID INT NOT NULL COMMENT 'PK - ID CENTRO EDUCATIVO',
	NAME VARCHAR(40) COMMENT 'NOMBRE CENTRO EDUCATIVO'

);

-- Eliminación de la columna número de teléfono.
ALTER TABLE FPD_NTTDATA_PEOPLE DROP COLUMN MOBILE_NUMBER;

-- Añadido de la columna nivel tecnológico.
ALTER TABLE FPD_NTTDATA_PEOPLE ADD COLUMN EMPLOYEE_RANK VARCHAR(30) COMMENT 'CATEGORÍA';

-- Insercciones de datos.
INSERT INTO FPD_NTTDATA_PEOPLE (PERSON_ID, NAME, IS_TRAINER, EMPLOYEE_RANK) VALUES (1, 'Alejandro Téllez', 1, 'CLD');

-- Creación de tabla para formadores. | Si se quiere no traer información igualar a condición falsa ej.: 1 = 2.
CREATE TABLE FPD_NTTDATA_TRAINER AS 
	SELECT NAME FROM FPD_NTTDATA_PEOPLE WHERE IS_TRAINER = true;
	
-- Eliminación de la tabla de personas.
DROP TABLE FPD_NTTDATA_PEOPLE;

-- Vaciar la tabla de formadores.
TRUNCATE TABLE FPD_NTTDATA_TRAINER;

-- Añadido de claves primarias.
ALTER TABLE FPD_NTTDATA_STUDENT ADD PRIMARY KEY(STUDENT_ID);

-- Añadido de constraints.
ALTER TABLE FPD_NTTDATA_SCHOOL ADD CONSTRAINT PK_SCHOOLID PRIMARY KEY (SCHOOL_ID);
ALTER TABLE FPD_NTTDATA_STUDENT ADD CONSTRAINT FK_SCHOOLID FOREIGN KEY (SCHOOL_ID) REFERENCES FPD_NTTDATA_SCHOOL(SCHOOL_ID);

-- Insercciones de datos.
INSERT INTO FPD_NTTDATA_STUDENT (STUDENT_ID, SCHOOL_ID, NAME) VALUES (1,1,"Ainara");
INSERT INTO FPD_NTTDATA_STUDENT (STUDENT_ID, SCHOOL_ID, NAME) VALUES (2,1,"Ainara");

-- Restricciones.
ALTER TABLE FPD_NTTDATA_STUDENT ADD CONSTRAINT UN_NAME UNIQUE(NAME);

-- Insercciones de datos.
INSERT INTO FPD_NTTDATA_SCHOOL (SCHOOL_ID, NAME) VALUES (1,"I.E.S. ALIXAR");
INSERT INTO FPD_NTTDATA_SCHOOL (SCHOOL_ID, NAME) VALUES (2,"I.E.S. CAMPANILLAS");
INSERT INTO FPD_NTTDATA_SCHOOL (SCHOOL_ID, NAME) VALUES (3,"I.E.S. HERMANOS MACHADO");
INSERT INTO FPD_NTTDATA_SCHOOL (SCHOOL_ID, NAME) VALUES (4,"I.E.S. PABLO PICASSO");
INSERT INTO FPD_NTTDATA_SCHOOL (SCHOOL_ID, NAME) VALUES (5,"I.E.S. SOTERO HERÁNDEZ");
INSERT INTO FPD_NTTDATA_SCHOOL (SCHOOL_ID, NAME) VALUES (6,"NTT DATA#1");
INSERT INTO FPD_NTTDATA_SCHOOL (SCHOOL_ID, NAME) VALUES (7,"CESUR (SEVILLA)");
INSERT INTO FPD_NTTDATA_SCHOOL (SCHOOL_ID, NAME) VALUES (8,"SALESIANAS DE MARÍA AUXILIDADORA");
INSERT INTO FPD_NTTDATA_SCHOOL (SCHOOL_ID, NAME) VALUES (9,"SANTA JOAQUINA DE VEDRUNA");
INSERT INTO FPD_NTTDATA_SCHOOL (SCHOOL_ID, NAME) VALUES (10,"NTT DATA#2");

-- Actualización de datos.
UPDATE FPD_NTTDATA_SCHOOL SET NAME = 'CESUR (MÁLAGA)' WHERE SCHOOL_ID = (SELECT SCHOOL_ID FROM FPD_NTTDATA_SCHOOL WHERE NAME = 'NTT DATA#1');

-- Eliminación de datos.
DELETE FROM FPD_NTTDATA_SCHOOL WHERE name = 'NTT DATA' AND SCHOOL_ID = (SELECT SCHOOL_ID FPD_NTTDATA_SCHOOL WHERE NAME = 'NTT DATA#2');